# Generated by Django 3.0.13 on 2021-03-05 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid
import variantenrichment.tool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('file', models.FileField(upload_to='')),
                ('population', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('37f81a13-7bc8-4f31-8713-98705cc2ea87'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('initial', 'Initial'), ('annotating', 'Annotating variants'), ('annotated', 'Ready for analysis'), ('analysing', 'Analysing data sets'), ('computing', 'Computing statistics'), ('done', 'Done')], default='initial', max_length=10)),
                ('impact', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='MODERATE', max_length=10)),
                ('frequency', models.DecimalField(decimal_places=5, default=0.001, max_digits=6)),
                ('filter_population', models.BooleanField(default=False)),
                ('cadd_score', models.IntegerField(blank=True, null=True)),
                ('mutation_taster_score', models.IntegerField(blank=True, null=True)),
                ('genes', models.FileField(blank=True, upload_to=variantenrichment.tool.models.get_project_directory)),
                ('background', models.ForeignKey(default=variantenrichment.tool.models.get_default_bgset, on_delete=django.db.models.deletion.SET_DEFAULT, to='tool.BackgroundSet')),
            ],
        ),
        migrations.CreateModel(
            name='VariantFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_name', models.CharField(max_length=20)),
                ('uploaded_file', models.FileField(upload_to=variantenrichment.tool.models.get_vcf_directory)),
                ('population', models.CharField(blank=True, max_length=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Project')),
            ],
        ),
    ]
