# Generated by Django 3.0.13 on 2021-03-09 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20210309_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundset',
            name='file',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('593ef939-5af5-4409-a334-faa1f2863957'), editable=False, primary_key=True, serialize=False),
        ),
    ]
