# Generated by Django 3.0.13 on 2021-03-11 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_auto_20210309_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('52283655-b1f0-458d-9dc4-0a771647954f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
