# Generated by Django 3.0.13 on 2021-03-13 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_auto_20210311_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Finished'), ('error', 'Error')], default='new', max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dc4c04e2-eda9-4a4f-8004-d9c3c03d5ce5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
