# Generated by Django 3.0.13 on 2021-05-28 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_auto_20210313_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='genes_exception',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_exception',
            field=models.CharField(blank=True, choices=[('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='impact',
            field=models.CharField(choices=[('MODERATE', 'Moderate'), ('HIGH', 'High')], default='MODERATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('initial', 'Initial'), ('annotating', 'Annotating variants'), ('annotated', 'Ready for CADD annotation or analysis'), ('cadd-annotating', 'Annotating with CADD functional scores'), ('cadd-annotated', 'Ready for analysis'), ('analysing', 'Analysing data sets'), ('computing', 'Computing statistics'), ('done', 'Done')], default='initial', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5f7a25ae-4f7f-4174-a6cb-74b6e6ed46a8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
