# Generated by Django 3.0.13 on 2021-06-03 15:54

from django.db import migrations, models
import uuid
import variantenrichment.tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_auto_20210603_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='inheritance',
            field=models.FileField(upload_to=variantenrichment.tool.models.get_project_directory),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('62b05977-924e-4e28-b1c7-dc0e466f1d47'), editable=False, primary_key=True, serialize=False),
        ),
    ]
