# Generated by Django 3.0.13 on 2021-06-25 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0012_auto_20210624_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cadd_file',
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0f43998d-7860-46e7-95e3-89ad59acb784'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CaddFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=60)),
                ('case_file', models.CharField(blank=True, max_length=20)),
                ('control_id', models.CharField(max_length=60)),
                ('control_file', models.CharField(blank=True, max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Project')),
            ],
        ),
    ]
