# Generated by Django 3.0.13 on 2021-06-25 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0013_auto_20210625_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caddfiles',
            old_name='case_file',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='caddfiles',
            old_name='control_file',
            new_name='control',
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3422ac71-f9e4-4db7-81b5-b142e9a07309'), editable=False, primary_key=True, serialize=False),
        ),
    ]
