# Generated by Django 3.0.13 on 2021-06-25 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0014_auto_20210625_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=30)),
                ('control', models.CharField(blank=True, max_length=30)),
                ('cadd_case_id', models.CharField(blank=True, max_length=60)),
                ('cadd_case', models.CharField(blank=True, max_length=20)),
                ('cadd_control_id', models.CharField(blank=True, max_length=60)),
                ('cadd_control', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cc08e88a-a71a-4989-8977-bba2c228fd94'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CaddFiles',
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Project'),
        ),
    ]
