# Generated by Django 3.0.13 on 2021-06-25 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_auto_20210625_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('42d90b31-ac04-438e-9b23-705d29d8d3c1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='cadd_case',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='cadd_control',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='case',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='control',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
