# Generated by Django 3.0.13 on 2021-06-25 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0017_auto_20210625_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='case_csv',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='control_csv',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='scores_csv',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('initial', 'Initial'), ('annotating', 'Annotating variants'), ('annotated', 'Ready for CADD annotation or analysis'), ('filtering', 'Filtering data sets'), ('cadd-waiting', 'Waiting for CADD answer'), ('cadd-checking', 'Checking if CADD scores are ready'), ('cadd-filtering', 'Annotating with CADD functional scores and filtering data sets by PHRED cutoff'), ('cadd-ready', 'Ready for analysis'), ('analyzing', 'Analyzing datasets and computing statistics'), ('done', 'Done')], default='initial', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3d7b0426-d5b0-4f03-9f0c-b8a7959176cf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
