# Generated by Django 3.0.13 on 2021-06-30 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0018_auto_20210625_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfiles',
            old_name='case',
            new_name='case_annotated',
        ),
        migrations.RenameField(
            model_name='projectfiles',
            old_name='control',
            new_name='case_filtered',
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='control_filtered',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('initial', 'Initial'), ('annotating', 'Annotating variants'), ('annotated', 'Ready for filtering'), ('filtering', 'Filtering data sets'), ('cadd-waiting', 'Waiting for CADD answer'), ('cadd-checking', 'Checking if CADD scores are ready'), ('cadd-filtering', 'Annotating with CADD functional scores and filtering data sets by PHRED cutoff'), ('analyzing', 'Analyzing datasets and computing statistics'), ('done', 'Done')], default='initial', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b35a2fd0-b4d6-4074-9598-6e31ec5858d4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
