# Generated by Django 3.0.13 on 2021-06-30 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0019_auto_20210630_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('33fcdb66-0ad4-4325-8fa9-ab06bec5e8ff'), editable=False, primary_key=True, serialize=False),
        ),
    ]
