# Generated by Django 3.0.13 on 2021-07-06 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0020_auto_20210630_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='filter_population',
        ),
        migrations.AddField(
            model_name='project',
            name='population',
            field=models.CharField(default='AFR,AMR,EAS,EUR,SAS', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('425660f7-b3d9-45ce-b1e0-249ff7660d1e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
