# Generated by Django 3.0.13 on 2021-07-06 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0021_auto_20210706_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='population',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5f6481d7-c660-493f-b728-e42edf2397a8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
