# Generated by Django 3.0.13 on 2021-07-13 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0022_auto_20210706_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantfile',
            name='population',
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('af8dd3a3-41bb-41e6-b463-d0f3852c115b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
