# Generated by Django 3.0.13 on 2021-07-16 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0026_remove_backgroundset_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundset',
            name='population',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=list, size=None),
        ),
    ]
