# Generated by Django 3.0.13 on 2021-07-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0027_backgroundset_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundset',
            name='population',
        ),
    ]
