# Generated by Django 3.0.13 on 2021-07-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0028_remove_backgroundset_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='population',
        ),
    ]
